### PR TITLE
Imasdk integration

### PR DESCRIPTION
**Pull request by ElBouhaliMohamed**
### Related:

Based on https://github.com/sampotts/plyr/blob/master/src/js/plugins/ads.js & https://github.com/glomex/vast-ima-player/blob/master/src/vast-ima-player.ts

### Description:

A "media-ads" component which enables users to show vast/vmap ads via the google IMA sdk. 

Test with https://gist.github.com/ElBouhaliMohamed/87efc074954179824645b767fc0fa80d in sandbox

### Ready?

Far from ready

### CODE REVIEW

**Comment by mihar-22** [comment]
Yo I appreciate this PR heaps, looks awesome!

There's a lot to review, caught a bunch of bugs on first glance. I can't review it right now because I have to get this next release `0.5` out in the next few but right after that I will.

Only things on my mind when I look at that right now is:

1. We probably need ad tracking on the main media store to do things like change the time slider.

2. I'm not familiar with ads libraries so where does this play exactly? How does it work? More my own research to do but if you have anything to share love to hear it.

3. We probably need some kind of ads integration layer the same we did with providers. I don't think it'd be a main component but rather a plugin of sorts? Could that work? For example, can we just set some stuff on the player like ads-x="..." and load the correct integration? What other integrations are there?

4. The other reason for ^ is because the component is too big to load by default. We need to lazy load something like ads.

**Comment by mihar-22** [comment]
Love the additions/changes, new direction is looking good! 

Some thoughts:

- We need to remap media requests (see `media-request-manager`) to be taken on the ad element instead of the current media. For example, if users plays, mutes, or fullscreens it should be redirected to the ad video element. We probably just need to look at at a flag on the media store inside existing request handlers.

- We probably should prevent loading this for audio? Not sure.

- We currently run all media events through the `MediaStateManager` (see `media-state-manager`) so we can centralize logic for updating the store and attaching requests (e.g., `media-play-request` on to a `play` event) - this is for analytics work later. In general, it helps identify system and user actions. To avoid additional event bindings we delegate to the state manager via the `MediaPlayerDelegate`. This would mean we need to call these methods from inside the `AdController` (e.g., `playerDelegate.handle('ad-play')`).

- Maybe instead of some the new ad props (e.g., `adPlaying`) we can just update existing state on the store? This way we don't need to remap everything in UI components. All we really need to know if whether an ad is running or not? I guess some things can't be merged like `adLoaded`, `adCanPlay`, `adCountdown`, etc.

Thanks for all your hard work on this, it means a lot. You don't have to respond to all my points above, feel free to process as needed 👍

**Comment by mihar-22** [comment]
Awesome!! I'll dig through after as soon as I can. Thanks for the update :)

**Comment by mihar-22** [comment]
I think the easiest way for me to test this is going to be if we have a skin first. This way I can get a better feel of how ads look and how the UI adapts when they're playing. We can circle back right after it and review the API too.

**Comment by zaied45-183** [comment]
Waiting for the IMA SDK

**Comment by alemosa** [comment]
Hello, any updates on this?
I could try to help if needed.

**Comment by mihar-22** [comment]
We'll get back to it after the next release since a lot of the core codebase will change.

**Comment by mihar-22** [comment]
I appreciate the work in this PR a lot but because of `1.0@next` rebuild it's outdated now. I'm more than happy to guide you in a new PR and get this added in. Most of the files have moved around slightly but you should comfortably be able to find them. You can kick off the new PR empty and start with questions if you like and we can go from there.

I'm sorry we broke this PR and all the hard work you put in, the rebuild and why it was needed is explained in the new release notes. I'd love to see this work go through, if you get a chance to start again love to help. Message me on Discord if you need anything too.

Thank you ❤️

**Pull request closed without merging**
