### PR TITLE
feat: add SMPTE timecodes

### LINKED ISSUE #809: Add support for SMPTE timecode
### Describe:

Add support form [SMPTE timecode](https://en.wikipedia.org/wiki/SMPTE_timecode) in player.

- [ ] Display the current time position in SMPTE timecode format *(video and audio)*
- [ ] Provide a starting timecode for a video track *(video and audio)*
- [ ] Enable frame-accurate playback *(video only)*

### Alternatives:

For reference - [VideoFrame - HTML5 Video SMPTE Time Code and Frame Seeking API](https://github.com/allensarkisyan/VideoFrame)

### Anything Else?

SMPTE timecode is presented in hour:minute:second:frame format, where sub-second timecode time values are expressed in terms of frames (instead of milliseconds), based on the video/audio framerate.

Most commonly used framerates: `23.976` (23.98), `24`, `25`, `29.97`, `30`, `59.94`, `60`

### PR DESCRIPTION
**Pull request by thehydrogen**
### Related:

This PR closes #809 

### Description:

This PR adds support to the `media-time` component for displaying SMPTE timecodes.

### Ready?

Yes. I would like to see if we have a better way of getting framerate than specifying it as a prop. This may require some deeper Vidstack/video knowledge from @mihar-22 

### Anything Else?

N/A

### Review Process:

Test enabling SMPTE timecodes on a video.

### CODE REVIEW

**Comment by thehydrogen** [comment]
If we can't find a way to programmatically get the frame rate, it might be preferable to specify it in `media-player` rather than in `media-time`.

**Comment by thehydrogen** [comment]
The validation error from GH Actions seems unrelated and can also be seen on #810

**Comment by mihar-22** [comment]
Awesome, thanks for the PR and getting on top of this. So, what we need is more complicated. We an API on the player for interacting with respect to frames. 

Very rough example:

```ts
interface MediaFrames {
  frame: number; // -1 if unknown
  rate: number; // provided or estimated
  toSMPTE(frame: number): string; // 
  fromSMPTE(smpte: string): number; // seconds
  seek(frame: number): void; // negative number seeks backwards
}

// ...

player.frames.seek(10);
```

Rough reference -> [LINK](https://github.com/allensarkisyan/VideoFrame#methods)

Additional requirements:

- A way to estimate frame rate. The user can provide this as concrete value or we estimate it. Media element and hls.js would most likey use different estimation techniques. Best to search around to see what options are available.
- Ability to provide starting timecode so media can seek to it immediately when ready for playback
- Displaying time code which you've implemented but it requires adjustment. Add to media context and make `frame` internally a signal which you can then use to format time. I think `useSmpte` is a little odd, probably `format="smpte"`.

**Comment by thehydrogen** [comment]
> * A way to estimate frame rate. The user can provide this as concrete value or we estimate it. Media element and hls.js would most likey use different estimation techniques. Best to search around to see what options are available.

This is the only solution I've found that (tested) works with HLS and *should* work with other providers

```ts
setInterval(() => {
  const quality = getUnderlyingVideo().getVideoPlaybackQuality();
  
  const fps = quality.totalVideoFrames - totalFrames;
  totalFrames = quality.totalVideoFrames;
}, 1000);
```

It's not ideal but I guess it could work for an estimation

**Comment by thehydrogen** [comment]
> * Displaying time code which you've implemented but it requires adjustment. Add to media context and make `frame` internally a signal which you can then use to format time[...]

Just to clarify, what are you referring to with "add to media context"?

**Comment by mihar-22** [comment]
The MediaFrames class

**Comment by thehydrogen** [comment]
> The MediaFrames class

Ah! Done, should be committing the first pass soon

**Comment by thehydrogen** [comment]
Frame-by-frame seeking is working as can be seen on https://vanillo.tv/v/6JXWI4yNkml

**Comment by mihar-22** [comment]
Awesome work @thehydrogen!!

Few change requests:

- `MediaFramesInstance` should just be `MediaFrames` and you can remove the interface. A class is essentially an interface.
- I don't see frame estimation code yet, might still be working on it? We can keep it separate and follow up, for now it can be simply defined on the player? Leave it up to you.
- Sync the player `frames` prop with store in `media-store-sync.ts`.
- Drop the `setByPlayer` and `noPlayerWarning` in `MediaFrames`. I see it was modelled after `MediaRemoteControl` but that's a little different since it can be created outside of the player component. The `MediaFrame` class is only an internal construct. Pass in the store to `MediaFrame` constructor if you need it. Do not pass in a player reference as that's over exposing.
- Format can be empty string `""` or `"smpte"`. 
- `formatTimeSmpte` repeats a lot of code in `formatTime`. Can we just use `formatTime` and then append frames suffix? I'm also wondering whether other options such as `padHours` and all that makes sense because SMPTE time code is expected in a particular format. Need to think about that API, let me know if you have ideas.

**Comment by thehydrogen** [comment]
> * `MediaFramesInstance` should just be `MediaFrames` and you can remove the interface. A class is essentially an interface.
Done!

> * I don't see frame estimation code yet, might still be working on it? We can keep it separate and follow up, for now it can be simply defined on the player via `frames` prop? Leave it up to you.
Yep still working on it. I'd love your feedback on [this suggestion](https://github.com/vidstack/player/pull/835#issuecomment-1558822548) - I don't personally love it but it seems like the only option.

> * Sync the player `frames` prop with store in `media-store-sync.ts`.
Done!

> * Drop the `setByPlayer` and `noPlayerWarning` in `MediaFrames`. I see it was modelled after `MediaRemoteControl` but that's a little different since it can be created outside of the player component. The `MediaFrame` class is only an internal construct. Pass in the store to `MediaFrame` constructor if you need it. Do not pass in a player reference as that's over exposing.
Done!

> * Format can be empty string `""` or `"smpte"`.
Done!

> * `formatTimeSmpte` repeats a lot of code in `formatTime`. Can we just use `formatTime` and then append frames suffix? I'm also wondering whether other options such as `padHours` and all that makes sense because SMPTE time code is expected in a particular format. Need to think about that API, let me know if you have ideas.
You're right that there's a specific format for SMPTE timecodes. I think we should keep `formatTimeSmpte` and remove the optional arguments for padding since those are already specified. Open to your feedback though!

**Comment by mihar-22** [comment]
I appreciate the work in this PR a lot but because of `1.0@next` rebuild it's outdated now. I'm more than happy to guide you in a new PR and get this added in. Most of the files have moved around slightly but you should comfortably be able to find them. You can kick off the new PR empty and start with questions if you like and we can go from there.

I'm sorry we broke this PR and all the hard work you put in, the rebuild and why it was needed is explained in the new release notes. I'd love to see this work go through, if you get a chance to start again love to help. Message me on Discord if you need anything too.

There's also some new suggestions on the issue around whether we can even accurately detect the video frame rate, so there might be some discussion needed around this feature.

Thank you ❤️

**Pull request closed without merging**
